-- ========================================================
-- SETUP DATABASE PROYEK FASTFOOD (Supabase / PostgreSQL)
-- ========================================================
-- Panduan: 
-- 1. Salin seluruh kode SQL di bawah ini.
-- 2. Buka dashboard Supabase kamu -> pilih Project kamu.
-- 3. Pilih menu "SQL Editor" di panel kiri.
-- 4. Klik "New query" -> Tempel (Paste) kode ini -> Klik "Run" (Jalankan).
-- ========================================================

-- 1. HAPUS TABEL JIKA SUDAH ADA (Untuk menghindari konflik)
DROP TABLE IF EXISTS public.restaurants CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. BUAT TABEL 'users'
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    pin TEXT,
    role TEXT NOT NULL,                  -- 'customer' | 'courier' | 'merchant'
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
    address TEXT,
    coords JSONB,                         -- Menyimpan { "lat": -7.123, "lng": 112.123 }
    plate_number TEXT,
    vehicle_type TEXT,
    sim_photo TEXT,
    document_file TEXT,
    shop_name TEXT,
    food_category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. BUAT TABEL 'restaurants'
CREATE TABLE public.restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating NUMERIC(3,2) DEFAULT 4.5,
    delivery_time TEXT DEFAULT '15-20 mnt',
    image TEXT,
    category TEXT,
    lat FLOAT8,                           -- Koordinat Lintang Peta
    lng FLOAT8,                           -- Koordinat Bujur Peta
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ATUR HAK AKSES KEAMANAN (Row Level Security / RLS)
-- Agar aplikasi React kamu bisa membaca dan menulis data secara langsung ke Supabase
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;

-- Polisi Hak Akses Tabel 'users'
CREATE POLICY "Allow public read" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.users FOR UPDATE USING (true);

-- Polisi Hak Akses Tabel 'restaurants'
CREATE POLICY "Allow public read" ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.restaurants FOR INSERT WITH CHECK (true);

-- 5. MASUKKAN DATA RESTORAN DEFAULT (MOCK DATA)
-- Restoran-restoran ini disesuaikan dengan koordinat geografis area Malang/Jawa Timur (atau ubah sesuai keinginan)
INSERT INTO public.restaurants (name, rating, delivery_time, image, category, lat, lng) VALUES
('Pizza Palace', 4.8, '15-20 mnt', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=200&fit=crop', 'Pizza', -7.9424, 112.6156),
('Burger Barn', 4.6, '10-15 mnt', 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=400&h=200&fit=crop', 'Burger', -7.9524, 112.6256),
('Pasta House', 4.7, '20-25 mnt', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=200&fit=crop', 'Pasta', -7.9624, 112.6356),
('Green Bowl', 4.5, '10-15 mnt', 'https://images.unsplash.com/photo-1565895405138-6c3a1555da6a?w=400&h=200&fit=crop', 'Sehat', -7.9724, 112.6456);
