-- ========================================================
-- SETUP DATABASE PROYEK FASTFOOD (Supabase / PostgreSQL)
-- ========================================================
-- Panduan: 
-- 1. Salin seluruh kode SQL di bawah ini.
-- 2. Buka dashboard Supabase kamu -> pilih Project kamu.
-- 3. Pilih menu "SQL Editor" di panel kiri.
-- 4. Klik "New query" -> Tempel (Paste) kode ini -> Klik "Run" (Jalankan).
-- ========================================================

-- 1. HAPUS TABEL JIKA SUDAH ADA (Untuk menghindari konflik)
DROP TABLE IF EXISTS public.restaurants CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. BUAT TABEL 'users'
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    pin TEXT,
    role TEXT NOT NULL,                  -- 'customer' | 'courier' | 'merchant'
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
    address TEXT,
    coords JSONB,                         -- Menyimpan { "lat": -7.123, "lng": 112.123 }
    plate_number TEXT,
    vehicle_type TEXT,
    sim_photo TEXT,
    document_file TEXT,
    shop_name TEXT,
    food_category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. BUAT TABEL 'restaurants'
CREATE TABLE public.restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating NUMERIC(3,2) DEFAULT 4.5,
    delivery_time TEXT DEFAULT '15-20 mnt',
    image TEXT,
    category TEXT,
    lat FLOAT8,                           -- Koordinat Lintang Peta
    lng FLOAT8,                           -- Koordinat Bujur Peta
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ATUR HAK AKSES KEAMANAN (Row Level Security / RLS)
-- Agar aplikasi React kamu bisa membaca dan menulis data secara langsung ke Supabase
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;

-- Polisi Hak Akses Tabel 'users'
CREATE POLICY "Allow public read" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.users FOR UPDATE USING (true);

-- Polisi Hak Akses Tabel 'restaurants'
CREATE POLICY "Allow public read" ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.restaurants FOR INSERT WITH CHECK (true);

-- 5. MASUKKAN DATA RESTORAN DEFAULT (MOCK DATA)
-- Restoran-restoran ini disesuaikan dengan koordinat geografis area Malang/Jawa Timur
INSERT INTO public.restaurants (name, rating, delivery_time, image, category, lat, lng) VALUES
('Pizza Palace', 4.8, '15-20 mnt', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=200&fit=crop', 'Pizza', -7.9424, 112.6156),
('Burger Barn', 4.6, '10-15 mnt', 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=400&h=200&fit=crop', 'Burger', -7.9524, 112.6256),
('Pasta House', 4.7, '20-25 mnt', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=200&fit=crop', 'Pasta', -7.9624, 112.6356),
('Green Bowl', 4.5, '10-15 mnt', 'https://images.unsplash.com/photo-1565895405138-6c3a1555da6a?w=400&h=200&fit=crop', 'Sehat', -7.9724, 112.6456);

-- 6. MASUKKAN DATA USER DEFAULT (MOCK DATA UNTUK LOGIN & DEMO)
INSERT INTO public.users (name, email, password, pin, role, status, address, coords, plate_number, vehicle_type, sim_photo, document_file, shop_name, food_category) VALUES
-- Akun Pelanggan (Customer) - Status Approved (bisa langsung login & belanja)
('Budi Santoso (Pelanggan)', 'pelanggan@fastfood.com', 'user123', '123456', 'customer', 'approved', 'Jl. Sukarno Hatta No. 15A, Lowokwaru, Malang', '{"lat": -7.9424, "lng": 112.6156}', NULL, NULL, NULL, NULL, NULL, NULL),

-- Akun Kurir (Courier) - Status Approved (bisa langsung terima order)
('Joko Susilo (Kurir)', 'kurir@fastfood.com', 'user123', NULL, 'courier', 'approved', 'Jl. Dinoyo No. 88, Lowokwaru, Malang', '{"lat": -7.9524, "lng": 112.6256}', 'N 1234 AB', 'Motor Bebek', 'https://images.unsplash.com/photo-1557223562-6c77ef16210f?w=200', NULL, NULL, NULL),

-- Akun Merchant (Restoran) - Status Approved (bisa kelola menu)
('Siti Aminah (Toko)', 'toko@fastfood.com', 'user123', NULL, 'merchant', 'approved', 'Jl. Gajayana No. 4, Lowokwaru, Malang', '{"lat": -7.9624, "lng": 112.6356}', NULL, NULL, NULL, 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=200', 'Warung Bu Siti', 'Nusantara'),

-- Akun Tambahan (Status Pending untuk simulasi Admin menyetujui akun)
('Andi Wijaya (Pending)', 'andi.pending@fastfood.com', 'user123', '123456', 'customer', 'pending', 'Jl. Borobudur No. 12, Malang', '{"lat": -7.9724, "lng": 112.6456}', NULL, NULL, NULL, NULL, NULL, NULL);
